# Generated by Django 4.0.1 on 2023-01-25 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='user_ud',
            field=models.BigIntegerField(default=None, unique=True, verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
