# Generated by Django 4.0.1 on 2023-01-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_user_ud_alter_tguser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='chat_id',
            new_name='tg_chat_id',
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='user_ud',
            new_name='tg_user_ud',
        ),
    ]
